(source gnu)
(source melpa)

(depends-on "auto-complete")
(depends-on "undo-tree")
(depends-on "helm")
(depends-on "php-mode")
(depends-on "point-undo")
(depends-on "flycheck")
(depends-on "rainbow-delimiters")
(depends-on "web-mode")