(source gnu)
(source melpa)
(source marmalade)

(depends-on "molokai-theme")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "ag")
(depends-on "company")
(depends-on "flycheck")
(depends-on "anzu")
(depends-on "undo-tree")
(depends-on "rainbow-delimiters")
(depends-on "php-mode")
(depends-on "php-cs-fixer" :git "https://github.com/kermorgant/php-cs-fixer.el.git")
(depends-on "company-php")
(depends-on "web-mode")
(depends-on "js2-mode")
(depends-on "yaml-mode")
(depends-on "json-mode")
(depends-on "markdown-mode")

