(source gnu)
(source melpa)
(source marmalade)

(depends-on "molokai-theme")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "ag")
(depends-on "company")
(depends-on "flycheck")
(depends-on "anzu")
(depends-on "undo-tree")
(depends-on "rainbow-delimiters")
(depends-on "php-mode")
(depends-on "phpcbf")
(depends-on "flycheck-phanclient" :git "https://github.com/TysonAndre/flycheck-phanclient.git")
(depends-on "company-php")
(depends-on "web-mode")
(depends-on "js2-mode")
(depends-on "yaml-mode")
(depends-on "json-mode")
(depends-on "markdown-mode")
(depends-on "editorconfig")
